# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17biRFt7WUTIKi97kiE1dCdJb3afq0hg-
"""

import streamlit as st
import torch
import numpy as np
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from gtts import gTTS
from io import BytesIO
import os

# --- 1. Configure the Page ---
st.set_page_config(page_title="Game Chat Moderator", page_icon="🎮", layout="wide")
st.title("🛡️ Game Chat Moderator")
st.markdown("I convert toxic game chat into hilarious, polite roasts. Try me!")

# --- 2. Load Models with Caching ---
@st.cache_resource
def load_toxicity_model():
    """Load the fine-tuned toxicity classification model."""
    model_path = "RachelHu123/toxic-comment-finetuned" # <--- IMPORTANT: Replace with your actual Hugging Face model ID
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForSequenceClassification.from_pretrained(model_path)
    return model, tokenizer

@st.cache_resource
def load_rewriter_model():
    """Load the pre-trained LLM for text rewriting."""
    model_name = "meta-llama/Llama-3.2-1B-Instruct"  # or "Qwen/Qwen2-1.5B-Instruct"
    return pipeline("text-generation", model=model_name, device_map="auto", torch_dtype=torch.float16)

# --- 3. Define Helper Functions ---

def is_toxic(text, model, tokenizer):
    """Classify if the input text is toxic."""
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
    # Adjust the index based on your fine-tuned model's label mapping (assuming index 1 is 'toxic')
    return probabilities[0][1].item() > 0.8  # Returns True if probability of 'toxic' > 80%

def rewrite_text(text, generator):
    """Rewrite toxic text using the LLM with a specific prompt."""
    prompt = f"""You are a polite British butler. Rewrite this rude game chat into a humorous, polite compliment.:
    Toxic text: "{text}"
    Rewritten text:"""
    output = generator(prompt, max_new_tokens=60, do_sample=True, temperature=0.7)[0]['generated_text']
    # Extract only the rewritten part after the prompt
    rewritten = output.split("Rewritten text:")[-1].strip()
    return rewritten

def text_to_speech(text):
    """Convert text to speech and return an audio file."""
    tts = gTTS(text, lang="en", slow=False)
    audio_fp = BytesIO()
    tts.write_to_fp(audio_fp)
    audio_fp.seek(0)
    return audio_fp

# --- 4. Load Models Once on Startup ---
with st.spinner("🔄 Loading models... This may take a moment on first run."):
    toxicity_model, toxicity_tokenizer = load_toxicity_model()
    rewriter_model = load_rewriter_model()

# --- 5. User Interface ---
user_input = st.text_area("Enter a game chat message:", height=150)

col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    analyze_button = st.button("🛡️ Purify Chat", use_container_width=True)

# --- 6. Main Logic: Analyze and Respond ---
if analyze_button and user_input:
    with st.spinner("🧠 Analyzing chat for toxicity..."):
        toxic = is_toxic(user_input, toxicity_model, toxicity_tokenizer)

    if toxic:
        with st.spinner("🪄 Crafting a humorous rewrite..."):
            polite_text = rewrite_text(user_input, rewriter_model)

        st.success("### ⚠️ Toxic Message Detected! Transforming...")
        with st.expander("See original toxic message"):
            st.write(f"**Original:** {user_input}")

        st.markdown(f"**✨ Purified Chat:** {polite_text}")

        with st.spinner("🔊 Generating speech..."):
            audio_file = text_to_speech(polite_text)
        st.audio(audio_file, format='audio/mp3')

    else:
        st.info("### ✅ Message is clean!")
        st.markdown(f"**Message:** {user_input}")

elif analyze_button and not user_input:
    st.warning("Please enter a message to analyze.")